# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-04 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161003_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_documents', models.FileField(upload_to='')),
            ],
        ),
    ]
