# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 06:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='message',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 6, 55, 23, 739325, tzinfo=utc)),
        ),
    ]
