# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-05 06:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161005_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 5, 6, 56, 58, 818962, tzinfo=utc)),
        ),
    ]
